# Testing Workflow

name: Example

on:
  push:
    branches: [ testing ]

jobs:
  example:
    runs-on: ubuntu-latest
    # Print repo details
    outputs:
      owner: ${{ steps.get-repo-details.outputs.owner }}
      repo: ${{ steps.get-repo-details.outputs.repo }}
    steps:
      - name: Get repo details
        id: get-repo-details
        run: |
          echo "owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
          echo "repo=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
        