name: EX2

on:
  push:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "hello World"

      - name: print_secret
        run: echo ${{ secrets.ENCRYPTION_KEY }}
        
